-- Stacks Quest Boards Database Initialization
-- Placeholder for any future database-backed features.

-- Example (PostgreSQL):
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- CREATE TABLE IF NOT EXISTS quest_events (
--   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--   quest_id TEXT NOT NULL,
--   user_id TEXT NOT NULL,
--   event_type TEXT NOT NULL,
--   payload JSONB,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
-- );